import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3b674b",
        "forest-deep": "#214D33",
        "error": "#ba1a1a",
        "surface-container": "#f1eee5",
        "surface-container-high": "#ece8df",
        "primary": "#06361e",
        "canvas-ivory": "#F7F3EA",
        "border-muted": "#E0D7C5",
        "forest-charcoal": "#1B3224",
        "primary-fixed-dim": "#a2d2af",
        "on-background": "#1c1c16",
        "error-container": "#ffdad6",
        "on-surface": "#1c1c16",
        "on-primary": "#ffffff",
        "surface": "#fdf9f0",
        "secondary": "#795900",
        "accent-terracotta": "#8F2D24",
        "on-primary-fixed-variant": "#234f35",
        "secondary-fixed-dim": "#eec05c",
        "surface-cream": "#EFE9DC",
        "inverse-on-surface": "#f4f0e7",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#261a00",
        "on-error-container": "#93000a",
        "inverse-primary": "#a2d2af",
        "outline": "#717972",
        "background": "#fdf9f0",
        "on-tertiary-fixed-variant": "#83251d",
        "tertiary": "#600a07",
        "on-tertiary-container": "#ff9487",
        "on-tertiary-fixed": "#410001",
        "secondary-fixed": "#ffdf9f",
        "surface-container-low": "#f7f3ea",
        "on-secondary": "#ffffff",
        "surface-dim": "#dddad1",
        "on-surface-variant": "#414942",
        "surface-container-highest": "#e6e2d9",
        "accent-gold": "#C49A3A",
        "tertiary-container": "#80221a",
        "secondary-container": "#fdce68",
        "outline-variant": "#c1c9c0",
        "on-primary-fixed": "#00210f",
        "tertiary-fixed-dim": "#ffb4aa",
        "primary-fixed": "#bdeeca",
        "on-secondary-container": "#765600",
        "surface-variant": "#e6e2d9",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad5",
        "gold-light": "#E8D5A3",
        "on-primary-container": "#8ebd9c",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-bright": "#fdf9f0",
        "inverse-surface": "#31302b",
        "primary-container": "#214d33",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1.5rem",
        "space-3xl": "6rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "4rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "2.5rem",
        "margin": "1.25rem"
      },
      fontFamily: {
        "display-lg-mobile": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "label-sm": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg": ["2.5rem", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.7", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "label-lg": ["0.875rem", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "headline-md": ["1.75rem", { "lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "500" }],
        "display-lg": ["3.5rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-md": ["0.75rem", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "label-sm": ["0.6875rem", { "lineHeight": "1.2", "letterSpacing": "0.12em", "fontWeight": "600" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "1.25", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.65", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.6", "letterSpacing": "0.015em", "fontWeight": "400" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
};
export default config;
